### ISSUE TITLE
Add support for additional languages

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/wikiloc#1]
Currently, it only works with the "he" version of Wikipedia, it'll be great if it could be easily adjusted to work with other languages based on the URL, for example, the URL "https://noam-honig.github.io/wikiloc/en" will search the English Wikipedia etc...

Bonus - figure out the user's language somehow and use that as the default

**Comment by ErezBiren** [comment]
I can take it.

**Comment by noam-honig** [comment]
Let's keep it hebrew for now :)
