### ISSUE TITLE
The background on social media is white on dark-mode

### ISSUE THREAD

**Issue by develad** [noam-honig/wikiloc#15]
![Screenshot_20230321-103215_Chrome](https://user-images.githubusercontent.com/70572668/226553800-b569e6ca-4a10-4ede-b862-c66253d6c51a.jpg)

**Comment by noam-honig** [comment]
It's an inner code from facebook and twitter - it works on chrome but not on ios :(

I've made a small bar with white backgronud as an interm solution :)
![image](https://user-images.githubusercontent.com/16635859/226565219-ae0f34d7-1a0a-440c-84db-289b0e3edfeb.png)
